spring:
  r2dbc:
    url: r2dbc:postgresql://postgres@localhost:5432/postgres
    name: postgres
    password: postgres

server:
  port: 9090

jwt:
  issuer: admin
  subject: auth
  expires-time: 3600
  secret: my-secret
